Bugfixes.
git-svn-id: https://svn.electricmonk.nl/svn/localenv/trunk@11 4da302af-41e2-4132-b91b-24f0e8d11e2d

diff --git a/localenv-confs b/localenv-confs
--- a/localenv-confs
+++ b/localenv-confs
@@ -16,13 +16,13 @@ function usage() {
 }
 
 function msg() {
-	if [ "$FLAG_VERBOSE" ]; then
-		echo $*
+	if [ -n "$FLAG_VERBOSE" ]; then
+		echo "$*" >&2
 	fi
 }
 
 function handle_cmdline() {
-	TEMP=`getopt -o hdp: --long dry-run,profile,help -n 'localenv-scripts' -- "$@"`
+	TEMP=`getopt -o hdvp: --long dry-run,profile,help,verbose -n 'localenv-scripts' -- "$@"`
 
 	if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
@@ -31,10 +31,11 @@ function handle_cmdline() {
 	while true ; do
 		case "$1" in
 			-d|--dry-run)  DRY_RUN=1;      shift 1;;
-			-p|--profile)  PROFILE=$2;     shift 2 ;;
-			-h|--help)     FLAG_HELP=1;    shift 1 ;;
-			--)                            shift 1; break ;;
-			*)             echo "Internal error!" ; exit 1 ;;
+			-p|--profile)  PROFILE=$2;     shift 2;;
+			-h|--help)     FLAG_HELP=1;    shift 1;;
+			-v|--verbose)  FLAG_VERBOSE=1; shift 1;;
+			--)                            shift 1; break;;
+			*)             echo "Internal error!" ; exit 1;;
 		esac
 	done
 
